36-View Component/Models/City.cs
namespace UsingViewComponents.Models {

    public class City {
        public string Name { get; set; }
        public string Country { get; set; }
        public int Population { get; set; }
    }
}

36-View Component/Models/CityRepository.cs
using System.Collections.Generic;

namespace UsingViewComponents.Models {

    public interface ICityRepository {
        IEnumerable<City> Cities { get; }

        void AddCity(City newCity);
    }

    public class MemoryCityRepository : ICityRepository {

        private List<City> cities = new List<City> {
            new City { Name = "London", Country = "UK", Population = 8539000},
            new City { Name = "New York", Country = "USA", Population = 8406000 },
            new City { Name = "San Jose", Country = "USA", Population = 998537 },
            new City { Name = "Paris", Country = "France", Population = 2244000 }
        };

        public IEnumerable<City> Cities => cities;

        public void AddCity(City newCity) {
            cities.Add(newCity);
        }
    }
}

36-View Component/Models/CityViewModel.cs
namespace UsingViewComponents.Models {

    public class CityViewModel {
        public int Cities { get; set; }
        public int Population { get; set; }
    }
}

36-View Component/Models/Product.cs
namespace UsingViewComponents.Models {

    public class Product {
        public string Name { get; set; }
        public decimal Price { get; set; }
    }
}

36-View Component/Models/ProductRepository.cs
using System.Collections.Generic;

namespace UsingViewComponents.Models {

    public interface IProductRepository {
        IEnumerable<Product> Products { get; }
        void AddProduct(Product newProduct);
    }

    public class MemoryProductRepository : IProductRepository {
        private List<Product> products = new List<Product> {
                new Product { Name = "Kayak", Price = 275M },
                new Product { Name = "Lifejacket", Price = 48.95M },
                new Product { Name = "Soccer ball", Price = 19.50M }
        };

        public IEnumerable<Product> Products => products;

        public void AddProduct(Product newProduct) {
            products.Add(newProduct);
        }
    }
}

36-View Component/Components/PocoViewComponent.cs
using System.Linq;
using UsingViewComponents.Models;

namespace UsingViewComponents.ViewComponents {

    public class PocoViewComponent {
        private ICityRepository repository;

        public PocoViewComponent(ICityRepository repo) {
            repository = repo;
        }

        public string Invoke() {
            return $"{repository.Cities.Count()} cities, "
                + $"{repository.Cities.Sum(c => c.Population)} people";
        }
    }
}

36-View Component/Controllers/CityController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using UsingViewComponents.Models;

namespace UsingViewComponents.Controllers {

    [ViewComponent(Name = "ComboComponent")]
    public class CityController : Controller {
        private ICityRepository repository;

        public CityController(ICityRepository repo) {
            repository = repo;
        }

        public ViewResult Create() => View();

        [HttpPost]
        public IActionResult Create(City newCity) {
            repository.AddCity(newCity);
            return RedirectToAction("Index", "Home");
        }

        public IViewComponentResult Invoke() => new ViewViewComponentResult() {
            ViewData = new ViewDataDictionary<IEnumerable<City>>(ViewData,
                repository.Cities)
        };
    }
}

36-View Component/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using UsingViewComponents.Models;

namespace UsingViewComponents.Controllers {

    public class HomeController : Controller {
        private IProductRepository repository;

        public HomeController(IProductRepository repo) {
            repository = repo;
        }

        public ViewResult Index() => View(repository.Products);

        public ViewResult Create() => View();

        [HttpPost]
        public IActionResult Create(Product newProduct) {
            repository.AddProduct(newProduct);
            return RedirectToAction("Index");
        }
    }
}

36-View Component/Views/City/Create.cshtml
@model City
@{
    ViewData["Title"] = "Create City";
    Layout = "_Layout";
}

<form method="post" asp-action="Create">
    <div class="form-group">
        <label asp-for="Name">Name:</label>
        <input class="form-control" asp-for="Name" />
    </div>
    <div class="form-group">
        <label asp-for="Country">Country:</label>
        <input class="form-control" asp-for="Country" />
    </div>
    <div class="form-group">
        <label asp-for="Population">Population:</label>
        <input class="form-control" asp-for="Population" />
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
    <a class="btn btn-secondary" asp-controller="Home"
       asp-action="Index">
        Cancel
    </a>
</form>

36-View Component/Views/Home/Components/CitySummary/CityList.cshtml
@model IEnumerable<City>

<table class="table table-sm table-bordered">
    @foreach (var city in Model) {
        <tr>
            <td>@city.Name</td>
            <td class="text-right">
                @city.Population.ToString("#,###")
            </td>
        </tr>
    }
    <tr>
        <th>Total:</th>
        <td class="text-right">
            @Model.Sum(p => p.Population).ToString("#,###")
        </td>
    </tr>
</table>

36-View Component/Views/Home/Components/CitySummary/Default.cshtml
@model CityViewModel

<table class="table table-sm table-bordered">
    <tr>
        <td>Cities:</td>
        <td class="text-right">
            @Model.Cities
        </td>
    </tr>
    <tr>
        <td>Population:</td>
        <td class="text-right">
            @Model.Population.ToString("#,###")
        </td>
    </tr>
</table>

36-View Component/Views/Shared/Components/ComboComponent/Default.cshtml
@model IEnumerable<City>

<table class="table table-sm table-bordered">
    <tr>
        <td>Biggest City:</td>
        <td>
            @Model.OrderByDescending(c => c.Population).First().Name
        </td>
    </tr>
</table>
<a class="btn btn-sm btn-info" asp-controller="City" asp-action="Create">
    Create City
</a>

36-View Component/Views/Shared/Components/PageSize/Default.cshtml
@model long
<div class="m-1 p-1 bg-info text-white">Page size: @Model</div>